### ISSUE TITLE
[Multilang] Gherkin should fail if keyword does not exists

### ISSUE THREAD

**Issue by wouterj** [Behat/Gherkin#86]
```
#language: nl
Functionaliteit: Xxxxxx

    Background:
        Given something is initialized

    Scenario: Yyyyyyy
         # ....
```

Loading the following spec should fail, since `Background` does not exists in the Dutch translation,  `Achtergrond` should be used instead. However, Gherkin simply ignores the Background now and continues parsing the features.
