### ISSUE TITLE
Behat Gherkin cache invalidation

### ISSUE THREAD

**Issue by emulgeator** [Behat/Gherkin#97]
First of all, I don't know how to reproduce this problem so I guess it will be pretty hard to find out the cause.
What happened is that on our CI server the behat tests started to fail for some reason and we found out that behat is running test cases what are not in the tested code base, but were in another branch.
So one branches feature file leaked into another branch after switching. 
We tried to invalidate opcode caches and check if there is anything cached maybe in the filesystem with no result. After a while we found a directory I wasn't aware of (/tmp/behat_gherkin_cache ) and just out of curiosity we removed it's content what fixed our tests again. Now we put a script into our CI process to remove the content of this directory before every run just in case.

**Comment by aaa2000** [comment]
You can also deactivate gherkin cache via the behat.yml file or via BEHAT_PARAMS Environment Variable.

Example:
```
default:
    suites:
        default:
            contexts:
                - FeatureContext:
    gherkin:
        cache: ~
```

or 

```
BEHAT_PARAMS='{"gherkin" : {"cache" : null}}' vendor/bin/behat
```
